Add haml
```
[sue445@sue445-MBP.local] ✓ ~/dev/workspace/github.com/sue445/ccc_privacy_crawler (feature/bundle_update)
[sue445@sue445-MBP.local] [05-16 20:58:43] $ be rspec
bundler: failed to load command: rspec (/Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/bin/rspec)
LoadError: cannot load such file -- haml
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/haml.rb:2:in `require'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/haml.rb:2:in `<top (required)>'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:243:in `require'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:243:in `block in lazy_load'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:241:in `each'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:241:in `lazy_load'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:216:in `lookup'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:154:in `[]'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt.rb:53:in `template_for'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:5:in `<module:OutputHelpers>'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:3:in `<module:Helpers>'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:2:in `<module:Padrino>'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:1:in `<top (required)>'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:23:in `require'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:23:in `block in glob_require'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `block in glob'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `each'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `glob'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:23:in `glob_require'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers.rb:9:in `<top (required)>'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-0.14.1/lib/padrino.rb:4:in `require'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/padrino-0.14.1/lib/padrino.rb:4:in `<top (required)>'
  /Users/sue445/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
  /Users/sue445/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
  /Users/sue445/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
  /Users/sue445/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
  /Users/sue445/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
  /Users/sue445/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
  /Users/sue445/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/config/boot.rb:12:in `<top (required)>'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/spec/spec_helper.rb:7:in `require'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/spec/spec_helper.rb:7:in `<top (required)>'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `require'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `block in requires='
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `each'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `requires='
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:111:in `each'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:21:in `configure'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:99:in `setup'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/exe/rspec:4:in `<top (required)>'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/bin/rspec:22:in `load'
  /Users/sue445/dev/workspace/github.com/sue445/ccc_privacy_crawler/vendor/bundle/ruby/2.4.0/bin/rspec:22:in `<top (required)>'
```